openapi: 3.0.3
info:
  title: Ping API
  version: 1.0.0
  description: Une API simple pour tester le ping
paths:
  /ping:
    get:
      summary: Vérifie si le serveur est vivant
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
