openapi: 3.0.3
info:
  title: User Management API
  version: 1.0.0

paths:
  /users:
    get:
      summary: Get a list of users
      description: Retourne une liste d'utilisateurs paginée.
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
            example: 1
        - name: size
          in: query
          required: true
          schema:
            type: integer
            example: 20
      responses:
        "200":
          description: Liste des utilisateurs retrouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "400":
          description: Mauvais types de paramètres fournis
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Bad types for provided query parameters

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          example: 3
        name:
          type: string
          example: jerry
        email:
          type: string
          example: jerry@example.com
