openapi: 3.0.3
info:
  title: API de gestion des tâches
  version: 1.0.1

paths:
  /tasks:
    get:
      summary: Obtenir toutes les tâches
      description: Retourne la liste complète des tâches existantes.
      responses:
        "200":
          description: Liste de toutes les tâches disponibles
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

    post:
      summary: Créer de nouvelles tâches
      description: Crée plusieurs nouvelles tâches envoyées dans le corps de la requête.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/TaskInput"
      responses:
        "201":
          description: Nouvelles tâches créées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"

  /tasks/{id}:
    get:
      summary: Obtenir une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche retrouvée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche introuvable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Supprimer une tâche par ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tâche supprimée
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Tâche introuvable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tasks:
    delete:
      summary: Supprimer plusieurs tâches
      description: Supprime plusieurs tâches en envoyant une liste d’identifiants.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: integer
                example: 3
      responses:
        "200":
          description: Liste de tâches supprimées
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "400":
          description: Mauvaise requête (liste d’ID invalide)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Faire les courses
        completed:
          type: boolean
          example: false

    TaskInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: Réviser mes cours
        completed:
          type: boolean
          example: false

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Ressource introuvable
